_wandb:
    value:
        cli_version: 0.25.1
        e:
            vvmsszedy0t8k3pvrn6534kjk41p2q6l:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "53687091200"
                        used: "36842770432"
                email: rony000013@gmail.com
                executable: X:\Python Projects\muscle_music\.venv\Scripts\python.exe
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-1143fbfc-8afa-4f86-9833-e78179050567
                host: BlackMamba
                memory:
                    total: "33595191296"
                os: Windows-11-10.0.26200-SP0
                program: X:\Python Projects\muscle_music\train.py
                python: CPython 3.13.11
                root: X:\Python Projects\muscle_music
                startedAt: "2026-04-10T15:22:12.605771Z"
                writerId: vvmsszedy0t8k3pvrn6534kjk41p2q6l
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.11
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 50
hop_length:
    value: 16
intensity_weight:
    value: 2
learning_rate:
    value: 0.001
n_fft:
    value: 64
